version: '3.5'
services:
  cars:
    links:
      - mysql


  payment_queue:
    image: cars:latest
    env_file: .env
    command: ["php", "artisan", "queue:work"]
    restart: on-failure
    links:
      - mysql


  mysql:
    image: mysql:5.7.13
    container_name: cars-mysql
    ports:
      - "${MY_SQL_PORT}:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql:
    driver: local
