version: '3.5'
services:
  cars:
    volumes:
      - ./:/var/www/html
    links:
      - mysql

  web:
    image: cars:latest
    working_dir: /var/www/html/resources/assets/js/desktop
    command: ["npm", "run", "start"]
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./:/var/www/html
    links:
      - cars

  mysql:
    image: mysql:5.7.13
    container_name: cars-mysql
    ports:
      - "${MY_SQL_PORT}:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ptran
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql:
    driver: local
